// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		403: typeof import("./src/components/error-message/403.vue")["default"];
		404: typeof import("./src/components/error-message/404.vue")["default"];
		500: typeof import("./src/components/error-message/500.vue")["default"];
		ElAside: typeof import("element-plus/es")["ElAside"];
		ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
		ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
		ElButton: typeof import("element-plus/es")["ElButton"];
		ElContainer: typeof import("element-plus/es")["ElContainer"];
		ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
		ElDrawer: typeof import("element-plus/es")["ElDrawer"];
		ElFooter: typeof import("element-plus/es")["ElFooter"];
		ElForm: typeof import("element-plus/es")["ElForm"];
		ElFormItem: typeof import("element-plus/es")["ElFormItem"];
		ElHeader: typeof import("element-plus/es")["ElHeader"];
		ElIcon: typeof import("element-plus/es")["ElIcon"];
		ElInput: typeof import("element-plus/es")["ElInput"];
		ElMain: typeof import("element-plus/es")["ElMain"];
		ElMenu: typeof import("element-plus/es")["ElMenu"];
		ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
		ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
		ElOption: typeof import("element-plus/es")["ElOption"];
		ElPageHeader: typeof import("element-plus/es")["ElPageHeader"];
		ElPagination: typeof import("element-plus/es")["ElPagination"];
		ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
		ElSelect: typeof import("element-plus/es")["ElSelect"];
		ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
		ElSwitch: typeof import("element-plus/es")["ElSwitch"];
		ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
		ElTag: typeof import("element-plus/es")["ElTag"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
	}
}
